config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'users/index'

  # root 'users#index'
  resources :posts, only: [:new, :show, :index]
  root "posts#index"

  resources :posts do
    member do
      put "like" => "posts#upvote"
      put "dislike" => "posts#downvote"
    end
  end

  resources :users, only: [:index, :show]
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  has_many :posts 
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :challenge
  belongs_to :user
  acts_as_votable

  has_attached_file :image, styles: { medium: "300x300>", thumb: "#100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  acts_as_voter
  has_attached_file :image, styles: { medium: "300x300>", thumb: "#100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  helper_method :challenge

  protected

  def configure_devise_permitted_parameters
    registration_params = [:username, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(registration_params)
      }
    end
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.all
  end

  # GET /posts/new
  def new
    count = current_user.posts.where('created_at > ?', 24.hours.ago).count
    if count >= 0
      @post = Post.new
      r = Random.new
      number = r.rand(1...25)
      @challenge = Challenge.find(number)
      @new_challenge = @challenge.content
      @post.challenge_id = @challenge.id
    else
        flash[:notice] = "You've already posted for today, come again tomorrow!"
        redirect_to '/posts'
    end
  end

  # GET /posts/1/edit
  def edit
    @posts = Post.all
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :challenge_id, :user_id, :image, :whatIdid, :whatIlearnt, :timestamps)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @posts = current_user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rejection Therapy</title>
    <link rel="stylesheet" href="/css/bootstrap.css" media="screen" title="no title" charset="utf-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="/js/bootstrap.js" charset="utf-8"></script>
    <link href='https://fonts.googleapis.com/css?family=Leckerli+One' rel='stylesheet' type='text/css'>

  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top" "nav">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="brand-name">
              <a href="#">Rejection Therapy</a>
            </li>
            <% if user_signed_in? %>
            <li><%= link_to 'New Post', new_post_path %></li>
            <% end %>
            <% if user_signed_in? %>
            <li><%= link_to 'Home', root_path %></li>
            <% end %>
            <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
          </ul>
          <div class="nav navbar-nav navbar-right">
            <% if current_user %>
          <li>
            <a href="/users/<%= current_user.id%>">
              <span class="glyphicon glyphicon-user"></span>
              <%= current_user.username %></a>
          </li>
          <% end %>
          <% if user_signed_in? %>
          <!-- <li><%= link_to('Logout', destroy_user_session_path, :method => :delete)%></li> -->
          <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "btn btn-default navbar-btn btn-sm")%>
        <% else %>
          <%= link_to("Sign Up", new_user_registration_path, :class => "btn btn-default navbar-btn btn-sm")  %>
          <%= link_to("Login", new_user_session_path, :class => "btn btn-default navbar-btn btn-sm")  %>
          <!-- <a class="btn btn-default" href="#" role="button"><%= link_to('Logout', destroy_user_session_path, :method => :delete)%></a> -->
          <% end %>
        </div>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class ="login-form">
  <div class="login-screen">
  <h1><b><%= timeago_tag Time.zone.now, format: "%a, %B %d" %>  </b></h1>
  <% if !@challenge.blank? %>
    <%=  @challenge.content  %>
  <% end %>
  <div class="field">
    <!-- <%= f.label :title %><br>
    <%= f.text_field :title %> -->
    <%= f.hidden_field :challenge_id, :value => @post.challenge_id %>
    <%= f.hidden_field :user_id, :value => @post.user_id %>
  </div>

<div class = "row">

  <div class="field" "questions">

    <div class="question"><%= f.label :whatIdid, "What did you do?"%><br></div>
    <div class="form-field"><%= f.text_area :whatIdid, :placeholder => "What did you do today?" %></div>
  </div>
  <div class="field" "questions">
    <div class="question"><%= f.label :whatIlearnt, "What did you learn?"%><br></div>
    <div class="form-field"><%= f.text_area :whatIlearnt, :placeholder => "What did you learn?"%></div>
  </div>

  </div>
  <div class="field">
    <%= f.label :image, " Image" %><br>
    <%= f.file_field :image %>
    <br />
  </div>
  <div class="actions" "btn btn-primary">
    <%= f.submit class:"btn btn-primary" %>

  </div>
</div>
</div>
<% end %>

app/views/posts/edit.html.erb
<div class="editing-stuff">Editing Post</div> 

<%= render 'form' %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="instructions" "header">
    <b>Hello
      <%= current_user.username %>, fill in today's entry
      <a href="/posts/new">here</a>
    </b>
  </div>

</div>
<% @posts.each do |post| %>
<div class="panel panel-default" "boxes">
  <div class="panel-heading">
    <div id="challenge-heading">
      <b><%= post.challenge.content unless post.challenge.blank? %></b>
    </div>
    <h5>
      <span class="glyphicon glyphicon-time"></span>
      Posted on
      <%= post.created_at.strftime('%b %d') %>
      by
      <%= post.user.username %></h5>
  </div>
  <div class= "body-posts">
    <% if !post.image.blank? %>
    <div class="panel-body" id="image-posts">
      <%=  image_tag post.image.url('medium'), class: "img-rounded" %>
    </div>
    <% end %>
    <div class="content-posts">

      <div class="panel-body">
        <p>
          <b>What I did:</b>
          <br/><%= post.whatIdid %></p>
      </div>
      <div class="panel-body">
        <p>
          <b>What I learnt:</b>
        </br><%= post.whatIlearnt %></p>
    </div>

  </div>
</div>
<div class="vote-button">

  <%= link_to like_post_path(post), class: "like", method: :put do %>
  <button type="button" class="btn btn-info" aria-label="Left Align">
    <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%=post.get_upvotes.size%>
    </span>
  </button>
  <% end %>

  <%= link_to dislike_post_path(post), class: "like", method: :put do %>
  <button type="button" class="btn btn-info" aria-label="Left Align">
    <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%=post.get_downvotes.size%>
    </span>
  </button>
  <% end %>
</div>
</div>

<!-- <button class="btn btn-default">
    <%= link_to "Edit", edit_post_path(post)%>
  </button> -->

<% end %>

</div>

app/views/posts/new.html.erb
<!-- <h1><%= timeago_tag Time.zone.now, format: "%a, %B %d" %></h1>

<% if !@challenge.blank? %>
  <%=  @challenge.content  %> -->

<!-- <p><%= timeago_tag Time.zone.now, format: "%a, %B %d" %></p> -->

<%= render 'form' %>
<% end %>

app/views/posts/show.html.erb
<% @posts.each do |post| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <div id="challenge-heading">
      <b><%= post.challenge.content unless post.challenge.blank? %></b>
    </div>
    <h5>
      <span class="glyphicon glyphicon-time"></span>
      Posted on
      <%= post.created_at.strftime('%b %d') %></h5>
  </div>
  <div class="body-posts">
    <% if !post.image.blank? %>
    <div class="panel-body" id="image-posts">
      <%=  image_tag post.image.url('medium'), class: "img-rounded" %>
    </div>
    <% end %>
    <div id="content-posts">

      <div class="panel-body">
        <p>
          <b>What I did:</b>
          <br/><%= post.whatIdid %></p>
      </div>
      <div class="panel-body">
        <p>
          <b>What I learnt:</b>
        </br><%= post.whatIlearnt %></p>
    </div>

  </div>
</div>

<div class="edit-button">

  <button class="btn btn-default" "edit-button">
    <%= link_to "Edit", edit_post_path(post)%>
  </button>

</div>

</div>

<% end %>

<style>

app/views/users/index.html.erb
<div class="header">
  <b>
    Users
  </b>
</div>

<% @users.each do |user| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <p><%= user.username %></p></div>
      <div class="panel-content">
        <p><%= user.email %></p></div>
    </div>
<% end %>

<style>

.header {
  font-size: 3rem;
  text-align: center;
  padding-bottom: 15px;
  color: white;
}

</style>